### ISSUE TITLE
ACF Image Field Rendering

### ISSUE THREAD

**Issue by stevebab** [humanmade/network-media-library#34] opened 2018-10-26 17:05 UTC
Incredibly helpful plugin. Thank you for your exceptional work and foresight. 

It seems that ACF image fields are using the id of the current blog rather than the network media source, and therefore return an empty array to the theme layer. 

I noticed that in version 1.2.0 that there is code about line 421 that forces galleries to use the network media source id. Would this be adaptable to also work with ACF?

**Comment by johnbillion** [comment] 2018-10-26 21:19
ACF support is one of the items on my todo list. I'm hoping that ACF has some filters in it that facilitate serving its media files from the central media site. It should be possible.

See #21.

**Comment by bedrijfsportaal** [comment] 2019-01-18 14:43
Hello,

Thank you for the incredibly helpful plugin, we still have issues regarding the ACF field rendering in combination with Gutenberg editor. 

When debugging the information below is generated with a HTTP 500 Error;
`post.php?post=5&action=edit&meta-box-loader=1&_wpnonce=82cecdefef&_locale=user | 500 `

When deactivating everything is working as expected.

**Comment by johnbillion** [comment] 2019-01-22 15:39
@bedrijfsportaal Are you able to check your PHP error logs to find out what's causing the 500? It might be a fatal error.

**Comment by fine-G** [comment] 2019-02-21 16:52
in the image crop and file field it is possible to add switch_blog() to bring them to work!

**Comment by raelshark** [comment] 2019-02-22 23:06
Came to say that I successfully used `switch_to_blog()` as mentioned above to get an ACF image field's content from my main site.

Here's a full example from inside a repeater field:

```
switch_to_blog(1);
$image = get_sub_field('photo');
restore_current_blog();
```

However, I'm currently stuck trying to get the same to work with an ACF options page image field. Using `switch_to_blog()` in that context gets back the corresponding option field for the switched blog - which is more of an ACF issue, but means the shared image can't be retrieved from the original source this way.

**Comment by raelshark** [comment] 2019-02-23 09:58
Okay, I figured out how to grab ACF images that are stored as options. The problem is in the "format" parameter on `get_field()` - it defaults to "true", which causes ACF to call `get_post()` on the image's ID, which we don't want because it looks for the image in the wrong blog.

So I was able to get it working by passing "false" for the "format" argument to `get_field()`, which gets back the image's ID, which we can then use to call `acf_get_attachment()` in the proper blog;

```php
$image_id = get_field('photo', 'option', false);
switch_to_blog( $main_blog );
$image = acf_get_attachment( $image_id, 'full' );
restore_current_blog();
```
Not sure if that's relevant to getting this working in NML, but hopefully it's helpful to someone.

**Comment by stevebab** [comment] 2019-02-26 12:45
Thanks for the post @raelshark

**Comment by johnbillion** [comment] 2019-03-07 20:59
Fixed in 1.5.0.

**Closed by johnbillion** 2019-03-07 20:59 UTC

**Comment by johnbillion** [comment] 2019-03-07 21:02
Thanks for those code pointers @raelshark, it helped a lot. Cheers!
